Repository kbsali/php-redmine-api, pull requests merged in 2024-07, with the labels that each got.

#409 Add `IssueStatus::listNames()` method as replacement for `IssueStatus::listing()`
  CHANGELOG.md
  src/Redmine/Api/IssueStatus.php
  tests/Behat/Bootstrap/IssueStatusContextTrait.php
  tests/Behat/features/issue_status.feature
  tests/Unit/Api/IssueStatus/ListNamesTest.php
  tests/Unit/Api/IssueStatusTest.php
Labels: enhancement

#410 Add health check for redmine services
  docker-compose.yml
  tests/RedmineExtension/BehatHookTracer.php
  tests/RedmineExtension/RedmineInstance.php
Labels: enhancement

#411 Add `Project::listNames()` method as replacement for `Project::listing()`
  CHANGELOG.md
  src/Redmine/Api/Project.php
  tests/Behat/Bootstrap/ProjectContextTrait.php
  tests/Behat/features/projects.feature
  tests/Unit/Api/Project/ListNamesTest.php
  tests/Unit/Api/ProjectTest.php
Labels: enhancement

#413 Support for many issue_categories
  tests/Behat/Bootstrap/IssueCategoryContextTrait.php
  tests/Behat/features/issue_category.feature
Labels: code quality

#412 Add `Role::listNames()` method as replacement for `Role::listing()`
  CHANGELOG.md
  src/Redmine/Api/Role.php
  tests/Behat/Bootstrap/RoleContextTrait.php
  tests/Behat/features/role.feature
  tests/Unit/Api/Role/ListNamesTest.php
  tests/Unit/Api/RoleTest.php
Labels: enhancement

#414 Add `TimeEntryActivity::listNames()` method as replacement for `TimeEntryActivity::listing()`
  CHANGELOG.md
  src/Redmine/Api/TimeEntryActivity.php
  tests/Behat/Bootstrap/TimeEntryActivityContextTrait.php
  tests/Behat/features/groups.feature
  tests/Behat/features/time_entry.feature
  tests/Behat/features/time_entry_activity.feature
  tests/Behat/features/user.feature
  tests/Unit/Api/TimeEntryActivity/ListNamesTest.php
  tests/Unit/Api/TimeEntryActivityTest.php
Labels: enhancement

#416 Add `Tracker::listNames()` method as replacement for `Tracker::listing()`
  CHANGELOG.md
  src/Redmine/Api/Tracker.php
  tests/Behat/Bootstrap/TrackerContextTrait.php
  tests/Behat/features/tracker.feature
  tests/Unit/Api/Tracker/ListNamesTest.php
  tests/Unit/Api/TrackerTest.php
Labels: enhancement

#420 Improve BDD with new testing command
  composer.json
  tests/Behat/README.md
Labels: enhancement

#419 Add `User::listLogins()` method as replacement for `User::listing()`
  CHANGELOG.md
  src/Redmine/Api/User.php
  tests/Behat/Bootstrap/UserContextTrait.php
  tests/Behat/features/user.feature
  tests/Unit/Api/User/ListLoginsTest.php
  tests/Unit/Api/UserTest.php
Labels: enhancement

#421 Add `Version::listNamesByProject()` method as replacement for `Version::listing()`
  CHANGELOG.md
  src/Redmine/Api/Version.php
  tests/Behat/Bootstrap/VersionContextTrait.php
  tests/Behat/features/version.feature
  tests/Unit/Api/Version/ListNamesByProjectTest.php
  tests/Unit/Api/VersionTest.php
Labels: enhancement

#422 Deprecate all `Redmine\Api\*::getIdBy...()` methods
  CHANGELOG.md
  src/Redmine/Api/CustomField.php
  src/Redmine/Api/Issue.php
  src/Redmine/Api/IssueCategory.php
  src/Redmine/Api/IssueStatus.php
  src/Redmine/Api/Project.php
  src/Redmine/Api/TimeEntryActivity.php
  src/Redmine/Api/Tracker.php
  src/Redmine/Api/User.php
  src/Redmine/Api/Version.php
  tests/Unit/Api/CustomFieldTest.php
  tests/Unit/Api/Issue/CreateTest.php
  tests/Unit/Api/Issue/UpdateTest.php
  tests/Unit/Api/IssueCategoryTest.php
  tests/Unit/Api/IssueStatusTest.php
  tests/Unit/Api/IssueTest.php
  tests/Unit/Api/ProjectTest.php
  tests/Unit/Api/TimeEntryActivityTest.php
  tests/Unit/Api/TrackerTest.php
  tests/Unit/Api/UserTest.php
  tests/Unit/Api/VersionTest.php
Labels: enhancement

#276 Remove development files from releases
  .gitattributes
Labels: enhancement, pending: await feedback

#424 Update docs
  README.md
  docs/usage.md
Labels: enhancement
